---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mongo
  namespace: default
  labels:
    app: hello-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-mongo
  template:
    metadata:
      labels:
        app: hello-mongo
    spec:
      containers:
      - name: hello-mongo
        image: us.gcr.io/zachy-dev/hello-mongo:v3
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: PYTHONBUFFERED
          value: "0"
        resources:
          requests:
            cpu: 1
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
