---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zach-webserver
  namespace: default
  labels:
    app: zach-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zach-webserver
  template:
    metadata:
      labels:
        app: zach-webserver
    spec:
      containers:
      - name: zach-webserver
        image: us.gcr.io/zachy-dev/zach-webserver:v4
        ports:
        - name: http
          containerPort: 8000
        - name: PYTHONBUFFERED
          value: "0"
        resources:
          requests:
            cpu: 1
            memory: 200Mi
          limits:
            cpu: 1
            memory: 200Mi
